### ISSUE TITLE
Issue with aws ec2 describe-tags command

### ISSUE THREAD

**Issue by techish-io** [BIAndrews/ec2tagfacts#15]
Puppet fails with timeout while running following command even though command itself works if I run it on terminal.

aws ec2 describe-tags --filters "Name=resource-id,Values=XXXXXXX" --region ap-southeast-2 --output json

If I take  this bit off "--region ap-southeast-2" it works fine.

I'm forking off this module to remove this bit as I don't have enough time to troubleshoot. Would you mind making this region param optional or ability to turn it off?

**Comment by ohmyish** [comment]
Fork is under https://github.com/techish1/ec2tagfacts

**Comment by BIAndrews** [comment]
Unable to reproduce
