### ISSUE TITLE
Missing "rescue" clause in ec2_tag_facts.rb

### ISSUE THREAD

**Issue by roiravhon** [BIAndrews/ec2tagfacts#2]
When first including the module, puppet copies ec2_tag_facts.rb into facter dir, before any configuration from the class getting enforced.

That's cause puppet run to fail on missing awscli command, or missing credentials if it's already installed.

I would suggest wrapping the awscli issue command and the json parsing with "begin rescue end" clauses which cause the script not to fail, and let puppet continue its run so it can configure everything else.

I have fixed that locally and it has managed to configure awscli after that.

**Comment by BIAndrews** [comment]
Would you please submit a PR with the code changes? Or if you aren't familiar with the process would you paste it here in the issue so I can? Big thanks!

**Comment by roiravhon** [comment]
Sure i'll submit a PR.
It will be tomorrow probably thought.

**Comment by BIAndrews** [comment]
Thank you! Merged and updated to the forge after testing locally on my systems.

**Comment by roiravhon** [comment]
Thanks. Awesome module by the way! simple and elegant
